# Builder image
FROM golang:latest as builder

COPY . /build

WORKDIR /build
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o val ./validator/...

# Exec image
FROM alpine:latest

COPY --from=builder /build/val /val

ENTRYPOINT ["/val"]
